# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: rust:1.35.0

before_script:
  - cargo version --verbose
  - rustup component add rustfmt

stages:
  - format
  - build
  - tests
  - examples

fmt:
  stage: format
  script:
      # When running with --check, Rustfmt will exit with 0 if Rustfmt would
      # not make any formatting changes to the input, and 1 if Rustfmt would
      # make changes.
    - cargo fmt --all --verbose -- --check --verbose

build:
  stage: build
  script:
    - cargo build --verbose

tests:
  stage: tests
  script:
    - cargo test

generative-tests:
  stage: tests
  script:
    - cargo test -- --ignored

build-doc:
  stage: tests
  script:
    - cargo doc

serde:
  stage: examples
  script:
    - cargo run --example serde

ternary:
  stage: examples
  script:
    - cargo run --example ternary
